### ISSUE TITLE
Register command not working

### ISSUE THREAD

**Issue by mamangBucin** [TakeFy/tkf_autowipe#1]
when i write /wipe in the chat is not showing the menu, how can I fix this?

**Comment by TakeFy** [comment]
Hi with the last version it should work ! do you have the last version available ?

**Comment by mamangBucin** [comment]
> Hi with the last version it should work ! do you have the last version available ?

i don't have it, how can i get it sir?

**Comment by TakeFy** [comment]
So you just need to download here https://github.com/TakeFy/tkf_autowipe/releases/tag/1.2 if you have any error in your f8 or console tell me

**Comment by TakeFy** [comment]
> > Hi with the last version it should work ! do you have the last version available ?
> 
> 
> 
> i don't have it, how can i get it sir?


So you just need to download here https://github.com/TakeFy/tkf_autowipe/releases/tag/1.2 if you have any error in your f8 or console tell me

**Comment by mamangBucin** [comment]
hello sir, i have no errors in my console, but it still not showing the menu :(

**Comment by TakeFy** [comment]
> hello sir, i have no errors in my console, but it still not showing the menu :(

Ok well can you open the server.lua file can you verify if you have all the table between line 41 - 62.

It's said to do this in the read.md file :)

**Comment by TakeFy** [comment]
> hello sir, i have no errors in my console, but it still not showing the menu :( 

If you don’t know how to fix it you can add me on discord TAKEFY#9831

**Comment by TakeFy** [comment]
Hi I fix the bug https://github.com/TakeFy/tkf_autowipe/releases/tag/1.3 can you follow the read.md file for the installation

**Comment by TakeFy** [comment]
@mamangBucin

**Comment by TakeFy** [comment]
[ace_perm.zip](https://github.com/TakeFy/tkf_autowipe/files/4924438/ace_perm.zip)
Fix in lastest 1.3 release
